# Generated by Django 2.1.4 on 2019-01-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='text',
            field=models.TextField(default='none'),
        ),
    ]
